name = "SpreadingDye"
uuid = "d2fc507f-b8c3-4645-b292-ec755ef5f34e"
authors = ["Michael Krabbe Borregaard <mkborregaard@sund.ku.dk> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
