name = "SpreadingDye"
uuid = "d2fc507f-b8c3-4645-b292-ec755ef5f34e"
authors = ["Michael Krabbe Borregaard <mkborregaard@sund.ku.dk> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
ArchGDAL = "c9ce4bd3-c3d5-55b8-8973-c0e20141b8c3"
Rasters = "a3a2b9e3-a471-40c9-b274-f788e487c689"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "ArchGDAL", "Rasters"]
